### ISSUE TITLE
unable to run

### ISSUE THREAD

**Issue by daeynasvistas** [openthingsio/OTF-Request-Proxy#4]
have problem when run npm start

ubuntu 18.04

```
OTF-Request-Proxy# npm start

> otf-request-proxy@0.0.0 start
> node js/server.js

node:internal/modules/cjs/loader:998
  throw err;
  ^

Error: Cannot find module '/var/www/OTF-Request-Proxy/js/server.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Function.Module._load (node:internal/modules/cjs/loader:841:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

```

**Comment by trbom5c** [comment]
I am experiencing this same issue. Is this repo up-to-date?

Any insights on how to overcome this issue?

```
superuser@mail:/var/www/otf/public_html/OTF-Request-Proxy$ npm start

> otf-request-proxy@0.0.0 start
> node js/server.js

node:internal/modules/cjs/loader:1137
  throw err;
  ^

Error: Cannot find module '/var/www/otf/public_html/OTF-Request-Proxy/js/server.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1134:15)
    at Module._load (node:internal/modules/cjs/loader:975:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.19.0
```

```
superuser@mail:/var/www/otf/public_html/OTF-Request-Proxy$ sudo cat /root/.npm/_logs/2024-05-30T07_08_31_646Z-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@6.14.6
3 info using node@v12.22.9
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle otf-request-proxy@0.0.0~prestart: otf-request-proxy@0.0.0
6 info lifecycle otf-request-proxy@0.0.0~start: otf-request-proxy@0.0.0
7 verbose lifecycle otf-request-proxy@0.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle otf-request-proxy@0.0.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/www/otf/public_html/OTF-Request-Proxy/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
9 verbose lifecycle otf-request-proxy@0.0.0~start: CWD: /var/www/otf/public_html/OTF-Request-Proxy
10 silly lifecycle otf-request-proxy@0.0.0~start: Args: [ '-c', 'node js/server.js' ]
11 silly lifecycle otf-request-proxy@0.0.0~start: Returned: code: 1  signal: null
12 info lifecycle otf-request-proxy@0.0.0~start: Failed to exec start script
13 verbose stack Error: otf-request-proxy@0.0.0 start: `node js/server.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1022:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid otf-request-proxy@0.0.0
15 verbose cwd /var/www/otf/public_html/OTF-Request-Proxy
16 verbose Linux 5.15.0-107-generic
17 verbose argv "/usr/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v12.22.9
19 verbose npm  v6.14.6
20 error code ELIFECYCLE
21 error errno 1
22 error otf-request-proxy@0.0.0 start: `node js/server.js`
22 error Exit status 1
23 error Failed at the otf-request-proxy@0.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by arfrie22** [comment]
You first need to run `npm run compile` I updated the README
